### ISSUE TITLE
[docs] Add Transaction Sending/Signing section to Android MWA Integration

### ISSUE THREAD

**Issue by Michaelsulistio** [solana-mobile/solana-mobile-doc-site#18]
The [Android MWA Integration guide](https://docs.solanamobile.com/android-native/quickstart) needs a section about Transaction Sending/Signing.
- signing transactions and signing messages.
- Bonus points if you want to add a section for signing and sending

The [React Native MWA Integration guide](https://docs.solanamobile.com/react-native/quickstart) already has a section and can be used as an example.

How to make changes
- Clone the repo
- Create your own branch for PR 
- Run `npm start` to start the docusaurus site on `localhost:3000`
- Edit `/docs/native-android/quickstart.md` and see changes reflected live
- Push up a PR when you're done and you can preview the vercel site
- when the PR is merged with main, it'll be auto deployed to prod.

**Comment by ritvij14** [comment]
@Michaelsulistio can I take up this one?

**Comment by Michaelsulistio** [comment]
Closed here:
https://docs.solanamobile.com/android-native/using_mobile_wallet_adapter
